# Generated by Django 4.2 on 2025-10-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('id_barbero', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('edad', models.CharField(blank=True, max_length=3, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'barbero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id_cita', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dia', models.CharField(blank=True, max_length=10, null=True)),
                ('hora', models.CharField(blank=True, max_length=6, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'citas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('edad', models.CharField(blank=True, max_length=3, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Duenio',
            fields=[
                ('id_duenio', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'duenio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_tipodepago', models.CharField(db_column='id_tipoDePago', max_length=10, primary_key=True, serialize=False)),
                ('tipodepago', models.CharField(blank=True, db_column='tipoDePago', max_length=25, null=True)),
            ],
            options={
                'db_table': 'pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id_resultado', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resultados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_servicio', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('servicio', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'servicios',
                'managed': False,
            },
        ),
    ]
